# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  Thank you and congrats 🎉 for opening your very first issue in this project. AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸 Please adhere to our [Code Of Conduct](http://systers.io/code-of-conduct).🙌🏻
  You may submit a PR on the same if you like! If you want to report a bug🐞, please follow our [bug_report.md](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) template. Also please make sure you include steps to reproduce it and be patient we will get back to you as soon as we can.👀
  Also feel free to join us on [AnitaB.org Open Source Zulip Community](https://anitab-org.zulipchat.com/).🤝 We have different streams for each active repo's for discussions.👩🏻‍💻🧑🏻‍💻
  Hope you have a great time here :) 

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  Thank you and congrats 🎉 for opening your first PR on this project.✨ We will review it soon! Till then you can checkout the `README.md` for more details on it.
  AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸 Please adhere to our [Code Of Conduct](http://systers.io/code-of-conduct).
  Also feel free to join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/).🤝 We have different streams for each active repo's for discussions.👩🏻‍💻🧑🏻‍💻
  Hope you have a great time here :) 

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Wohoo!🎊 Congrats on merging your first pull request!🙈
  Feel free to explore more on this project.🤗
  Join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/).🤝 We have different streams for each active repo's for discussions.👩🏻‍💻🧑🏻‍💻 Do join our weekly check-in stream to share your weekly goals and the awesome work you did here.😃
  Now that you've completed this, you can help someone else take their first step! Check out projects stream on Zulip and the `first-timer-only` issues to check if someone need help to figure out their problem or need some feedbacks. Reach out and be encouraging and friendly! 😄 🎉


# It is recommended to include as many gifs and emojis as possible!
